---
- hosts: webserver
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u mohithdevops9@gmail.com -p Manvith@123 mohitrrr.jfrog.io   
    
    - name: pull an image
      shell: docker pull mohitrrr.jfrog.io/testdocker/war_on_container:v{{ BUILD_NUMBER }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 mohitrrr.jfrog.io/testdocker/war_on_container:v{{ BUILD_NUMBER }}
 
   
